import { AgentSpec, HarnessFiles } from '../types/schemas.js';

/**
 * Generates a complete agent harness from an agent spec.
 * 
 * This is the core of the framework - it takes a high-level agent description
 * and produces all the files needed to run and evaluate that agent.
 */
export async function generateHarness(spec: AgentSpec): Promise<HarnessFiles> {
  const soul = generateSoulMd(spec);
  const agents = generateAgentsMd(spec);
  const memory = generateMemoryMd(spec);
  const learnings = generateLearningsMd(spec);
  const tests = generateTestSuite(spec);
  const runtimeAdapter = generateRuntimeAdapter(spec);
  
  return {
    soul,
    agents,
    memory,
    learnings,
    tests,
    runtimeAdapter,
  };
}

function generateSoulMd(spec: AgentSpec): string {
  return `# SOUL.md — ${spec.role}

## Identity
You are **${spec.agentId}** — ${spec.role.toLowerCase()}.

**Voice:** ${getVoiceForRole(spec.role)}

## Core Responsibilities
${spec.responsibilities.map((r, i) => `${i + 1}. **${r}**`).join('\n')}

## Rules (MANDATORY)
1. **Stay in role** — You are ${spec.agentId}. Do not take on tasks outside your responsibilities.
2. **One thing at a time** — Work incrementally. Complete one subtask before moving to the next.
3. **Leave clean state** — Always end your session with:
   - Progress documented in MEMORY.md
   - Work committed to git (if applicable)
   - Next steps clearly written
4. **Test before marking done** — Never declare a feature complete without verification.
5. **Learn from errors** — Append to LEARNINGS.md after every session with what worked and what didn't.

## Tools Available
${spec.tools.map(t => `- **${t.name}** (${t.type}): ${t.description || 'No description'}`).join('\n')}

## Workflow
${spec.plan}

## Meta-Learning (MANDATORY)
After every task, append to LEARNINGS.md:
\`\`\`
### [Date] — [Task summary]
- **What worked:** [specific technique]
- **What didn't:** [what failed or was slow]
- **Pattern discovered:** [reusable insight]
- **Files touched:** [list]
\`\`\`

No exceptions. This is how you improve across sessions.

---
*Generated by Harness Trainer v0.1.0*
`;
}

function generateAgentsMd(spec: AgentSpec): string {
  return `# AGENTS.md — Operations Manual for ${spec.agentId}

## Every Session (MANDATORY)

**Step 1: Orient** — Read MEMORY.md to understand current state.
**Step 2: Plan** — Identify the next highest-priority task.
**Step 3: Execute** — Work on ONE task at a time.
**Step 4: Verify** — Test your work before marking complete.
**Step 5: Document** — Update MEMORY.md and LEARNINGS.md.

## Tool Usage Patterns

${spec.tools.map(t => generateToolPattern(t)).join('\n\n')}

## Error Handling

When you encounter an error:
1. **Log it** — Write the error to MEMORY.md immediately
2. **Diagnose** — What caused this? Missing context? Tool failure? Logic error?
3. **Recover** — Try a different approach or ask for clarification
4. **Learn** — Add to LEARNINGS.md what to avoid next time

## Handoff Protocol

If you need to delegate or hand off:
1. Write clear context in MEMORY.md
2. Specify what's done vs. what's remaining
3. Note any blockers or gotchas
4. Tag the appropriate sub-agent or human

## Success Criteria

You are successful when:
- ${spec.responsibilities.map(r => `You consistently ${r.toLowerCase()}`).join('\n- ')}
- Your LEARNINGS.md grows with actionable insights
- You leave clean state after every session

---
*Generated by Harness Trainer v0.1.0*
`;
}

function generateMemoryMd(spec: AgentSpec): string {
  return `# MEMORY.md — ${spec.agentId}

## Active Right Now

### Current Task
<!-- Update this every session -->
- **Working on:** [description]
- **Started:** [date]
- **Status:** [in progress | blocked | complete]

### Recent Progress
<!-- Last 3-5 sessions -->
- [Date] — [What was accomplished]
- [Date] — [What was accomplished]

### Blockers
<!-- Things preventing progress -->
- [ ] [blocker description]

### Next Up
<!-- Priority queue of next tasks -->
1. [ ] [next task]
2. [ ] [following task]
3. [ ] [future task]

## Session Context

### What I'm Running On
- **Runtime:** ${spec.runtime}
- **Model:** ${spec.model?.primary || 'default'}
- **Workspace:** ${spec.workspace || `./agent-workspaces/${spec.agentId}`}

### Key Files
- SOUL.md — Identity and rules
- AGENTS.md — Operations manual
- LEARNINGS.md — Self-improvement log
- tests/eval-suite.json — Test cases

---
*This file is updated every session. Keep it lean — archive old context.*
`;
}

function generateLearningsMd(spec: AgentSpec): string {
  return `# LEARNINGS.md — ${spec.agentId}

## Session Log

<!-- Append after every task. No exceptions. -->

### ${new Date().toISOString().split('T')[0]} — Harness Generated
- **What worked:** Harness Trainer generated initial SOUL.md, AGENTS.md, and test suite
- **What didn't:** N/A — initial setup
- **Pattern discovered:** N/A — awaiting first training iteration
- **Files touched:** SOUL.md, AGENTS.md, MEMORY.md, LEARNINGS.md, eval-suite.json

---
*This is how the agent improves. Every session adds a entry.*
`;
}

function generateTestSuite(spec: AgentSpec): HarnessFiles['tests'] {
  // Generate test cases based on responsibilities
  return spec.responsibilities.map((resp, i) => ({
    name: `test_${spec.agentId}_responsibility_${i + 1}`,
    description: `Verify agent can: ${resp}`,
    input: `Task: ${resp}. Success criteria: Complete the task while following all rules in SOUL.md.`,
    expectedOutput: `Task completed successfully with clean state, documented progress, and passing verification.`,
    scoringRubric: {
      taskCompletion: 0.4,
      errorRecovery: 0.25,
      cleanState: 0.2,
      tokenEfficiency: 0.1,
      selfLearn: 0.05,
    },
  }));
}

function generateRuntimeAdapter(spec: AgentSpec): string {
  const adapterType = spec.runtime;
  
  if (adapterType === 'openclaw') {
    return `// OpenClaw Runtime Adapter for ${spec.agentId}
// This adapter integrates the harness with OpenClaw's session management

export async function spawnAgent(task, options = {}) {
  const { sessions_spawn } = await import('openclaw:tools');
  
  return await sessions_spawn({
    agentId: '${spec.agentId}',
    mode: options.mode || 'run',
    model: '${spec.model?.primary || 'anthropic/claude-sonnet-4-6'}',
    task: task,
    timeoutSeconds: options.timeout || 1800,
  });
}

export async function getAgentOutput(sessionKey) {
  const { sessions_history } = await import('openclaw:tools');
  
  const history = await sessions_history({
    sessionKey: sessionKey,
    includeTools: true,
  });
  
  return history;
}

export const runtimeConfig = {
  type: 'openclaw',
  supportsStreaming: true,
  supportsSubagents: true,
  maxConcurrent: 8,
};
`;
  }
  
  if (adapterType === 'claude-code') {
    return `// Claude Code Runtime Adapter for ${spec.agentId}
// This adapter integrates the harness with Claude Code CLI

import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export async function spawnAgent(task, options = {}) {
  const claudeArgs = [
    '--prompt',
    JSON.stringify(task),
    options.model ? \`--model \${options.model}\` : '',
  ].filter(Boolean).join(' ');
  
  const { stdout, stderr } = await execAsync(\`claude \${claudeArgs}\`);
  
  return {
    output: stdout,
    error: stderr,
    sessionKey: null, // Claude Code doesn't have persistent sessions
  };
}

export async function getAgentOutput(sessionKey) {
  throw new Error('Claude Code adapter does not support session retrieval');
}

export const runtimeConfig = {
  type: 'claude-code',
  supportsStreaming: false,
  supportsSubagents: false,
  maxConcurrent: 1,
};
`;
  }
  
  // Custom adapter template
  return `// Custom Runtime Adapter for ${spec.agentId}
// Implement the adapter interface for your custom runtime

export async function spawnAgent(task, options = {}) {
  // TODO: Implement agent spawning for your runtime
  throw new Error('Not implemented');
}

export async function getAgentOutput(sessionKey) {
  // TODO: Implement output retrieval for your runtime
  throw new Error('Not implemented');
}

export const runtimeConfig = {
  type: 'custom',
  supportsStreaming: false,
  supportsSubagents: false,
  maxConcurrent: 1,
};
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function getVoiceForRole(role: string): string {
  const roleLower = role.toLowerCase();
  if (roleLower.includes('research')) return 'Analytical, curious, thorough. Cite sources.';
  if (roleLower.includes('engineer') || roleLower.includes('dev')) return 'Technical, precise, pragmatic. Code-first.';
  if (roleLower.includes('writer') || roleLower.includes('content')) return 'Creative, engaging, clear. Voice matters.';
  if (roleLower.includes('coach') || roleLower.includes('lifecoach')) return 'Supportive, direct, action-oriented. Push growth.';
  if (roleLower.includes('financial') || roleLower.includes('tax')) return 'Conservative, detail-oriented, compliant. Numbers first.';
  if (roleLower.includes('architect')) return 'Strategic, opinionated, well-researched. Design patterns matter.';
  return 'Professional, helpful, efficient. Get the job done.';
}

function generateToolPattern(tool: any): string {
  return `### ${tool.name}
**When to use:** [context where this tool is appropriate]
**How to use:** 
\`\`\`
// Example usage
\`\`\`
**Common pitfalls:** [what goes wrong]
**Error handling:** [how to recover]`;
}
