import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { AgentSpec, HarnessFiles } from '../types/schemas.js';

interface GenerateOptions {
  spec: AgentSpec;
  outputDir: string;
  force?: boolean;
}

/**
 * Generates a complete agent workspace from an agent spec.
 * 
 * This is the core of the framework - it takes a high-level agent description
 * and produces all the files needed to run and evaluate that agent.
 */
export async function generateHarness(options: GenerateOptions): Promise<string> {
  const { spec, outputDir, force = false } = options;
  
  // Create workspace directory
  const workspacePath = join(outputDir, spec.agentId);
  
  if (existsSync(workspacePath) && !force) {
    throw new Error(`Workspace already exists at ${workspacePath}. Use --force to overwrite.`);
  }
  
  console.log(chalk.dim(`   Creating workspace: ${workspacePath}`));
  mkdirSync(workspacePath, { recursive: true });
  
  // Generate all files
  const files = generateAllFiles(spec);
  
  // Write harness files
  const harnessDir = join(workspacePath, 'harness');
  mkdirSync(harnessDir, { recursive: true });
  
  writeFileSync(join(harnessDir, 'SOUL.md'), files.soul);
  writeFileSync(join(harnessDir, 'AGENTS.md'), files.agents);
  writeFileSync(join(harnessDir, 'MEMORY.md'), files.memory);
  writeFileSync(join(harnessDir, 'LEARNINGS.md'), files.learnings);
  
  // Write tests
  const testsDir = join(workspacePath, 'tests');
  mkdirSync(testsDir, { recursive: true });
  writeFileSync(join(testsDir, 'eval-suite.json'), files.tests);
  
  // Write runtime adapter
  const runtimeDir = join(workspacePath, 'runtime');
  mkdirSync(runtimeDir, { recursive: true });
  writeFileSync(join(runtimeDir, 'adapter.js'), files.runtimeAdapter);
  
  // Write spec copy for reference
  writeFileSync(join(workspacePath, 'spec.json'), JSON.stringify(spec, null, 2));
  
  console.log(chalk.dim(`   ✓ Written: harness/SOUL.md`));
  console.log(chalk.dim(`   ✓ Written: harness/AGENTS.md`));
  console.log(chalk.dim(`   ✓ Written: harness/MEMORY.md`));
  console.log(chalk.dim(`   ✓ Written: harness/LEARNINGS.md`));
  console.log(chalk.dim(`   ✓ Written: tests/eval-suite.json`));
  console.log(chalk.dim(`   ✓ Written: runtime/adapter.js`));
  console.log(chalk.dim(`   ✓ Written: spec.json`));
  
  return workspacePath;
}

function generateAllFiles(spec: AgentSpec): HarnessFiles {
  return {
    soul: generateSoulMd(spec),
    agents: generateAgentsMd(spec),
    memory: generateMemoryMd(spec),
    learnings: generateLearningsMd(spec),
    tests: generateTestSuite(spec),
    runtimeAdapter: generateRuntimeAdapter(spec),
  };
}

function generateSoulMd(spec: AgentSpec): string {
  return `# SOUL.md — ${spec.role}

## Identity
You are **${spec.agentId}** — ${spec.role.toLowerCase()}.

**Voice:** ${getVoiceForRole(spec.role)}

## Core Responsibilities
${spec.responsibilities.map((r, i) => `${i + 1}. **${r}**`).join('\n')}

## Rules (MANDATORY)
1. **Stay in role** — You are ${spec.agentId}. Do not take on tasks outside your responsibilities.
2. **One thing at a time** — Work incrementally. Complete one subtask before moving to the next.
3. **Leave clean state** — Always end your session with:
   - Progress documented in MEMORY.md
   - Work committed to git (if applicable)
   - Next steps clearly written
4. **Test before marking done** — Never declare a feature complete without verification.
5. **Learn from errors** — Append to LEARNINGS.md after every session with what worked and what didn't.

## Tools Available
${spec.tools.map(t => `- **${t.name}** (${t.type}): ${t.description || 'No description'}`).join('\n')}

## Workflow
${spec.plan}

## Meta-Learning (MANDATORY)
After every task, append to LEARNINGS.md:
\`\`\`
### [Date] — [Task summary]
- **What worked:** [specific technique]
- **What didn't:** [what failed or was slow]
- **Pattern discovered:** [reusable insight]
- **Files touched:** [list]
\`\`\`

No exceptions. This is how you improve across sessions.

---
*Generated by Harness Trainer v0.1.0*
`;
}

function generateAgentsMd(spec: AgentSpec): string {
  return `# AGENTS.md — Operations Manual for ${spec.agentId}

## Every Session (MANDATORY)

**Step 1: Orient** — Read MEMORY.md to understand current state.
**Step 2: Plan** — Identify the next highest-priority task.
**Step 3: Execute** — Work on ONE task at a time.
**Step 4: Verify** — Test your work before marking complete.
**Step 5: Document** — Update MEMORY.md and LEARNINGS.md.

## Tool Usage Patterns

${spec.tools.map(t => generateToolPattern(t)).join('\n\n')}

## Error Handling

When you encounter an error:
1. **Log it** — Write the error to MEMORY.md immediately
2. **Diagnose** — What caused this? Missing context? Tool failure? Logic error?
3. **Recover** — Try a different approach or ask for clarification
4. **Learn** — Add to LEARNINGS.md what to avoid next time

## Handoff Protocol

If you need to delegate or hand off:
1. Write clear context in MEMORY.md
2. Specify what's done vs. what's remaining
3. Note any blockers or gotchas
4. Tag the appropriate sub-agent or human

---
*Generated by Harness Trainer v0.1.0*
`;
}

function generateMemoryMd(spec: AgentSpec): string {
  return `# MEMORY.md — ${spec.agentId}

## Active Context

_This file contains current, active information needed for the agent to function._

### Current Tasks
- [ ] No tasks assigned yet

### Recent Learnings
_None yet — run your first task to populate_

### State
- **Last session:** [Date]
- **Current focus:** [What you're working on]
- **Blockers:** [Any blockers]

---

_Historical context should be moved to vector DB or archived. Keep this file lean._

*Generated by Harness Trainer v0.1.0*
`;
}

function generateLearningsMd(spec: AgentSpec): string {
  return `# LEARNINGS.md — ${spec.agentId}

## Session Log

_Append after every session. This is how the agent improves across runs._

### [Date] — First Session
- **What worked:** Initial harness generation
- **What didn't:** N/A
- **Pattern discovered:** N/A
- **Files touched:** SOUL.md, AGENTS.md, MEMORY.md

---

*Generated by Harness Trainer v0.1.0*
`;
}

function generateTestSuite(spec: AgentSpec): string {
  const tests = generateDefaultTests(spec);
  
  return JSON.stringify({
    version: '1.0',
    agentId: spec.agentId,
    description: `Evaluation suite for ${spec.agentId}`,
    tests,
  }, null, 2);
}

function generateDefaultTests(spec: AgentSpec): any[] {
  // Generate sensible default tests based on agent responsibilities
  return spec.responsibilities.map((resp, i) => ({
    name: `test-${i + 1}-${slugify(resp.split(' ')[0])}`,
    description: `Test: ${resp}`,
    task: `Perform the following responsibility: ${resp}`,
    expectedOutput: `Agent should complete the responsibility successfully and document the process.`,
    successCriteria: [
      'Task completed end-to-end',
      'Progress documented in MEMORY.md',
      'Learnings appended to LEARNINGS.md',
      'No errors or unhandled exceptions',
    ],
  }));
}

function generateRuntimeAdapter(spec: AgentSpec): string {
  const adapterType = spec.runtime || 'openclaw';
  
  if (adapterType === 'openclaw') {
    return `// OpenClaw Runtime Adapter for ${spec.agentId}
// This adapter integrates the harness with OpenClaw's session management

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

/**
 * Spawns an agent using OpenClaw's sessions_spawn API.
 */
export async function spawnAgent(task, options = {}) {
  // This would be called from within OpenClaw context
  // For standalone execution, we simulate with a placeholder
  
  console.log('Spawning agent with task:', task);
  console.log('Model:', '${spec.model?.primary || 'anthropic/claude-sonnet-4-6'}');
  
  // In production, this would call:
  // const { sessions_spawn } = await import('openclaw:tools');
  // return await sessions_spawn({ agentId: '${spec.agentId}', ... });
  
  return {
    sessionKey: 'simulated-session-key',
    status: 'running',
  };
}

/**
 * Retrieves agent output from a completed session.
 */
export async function getAgentOutput(sessionKey) {
  // In production, this would call:
  // const { sessions_history } = await import('openclaw:tools');
  // return await sessions_history({ sessionKey, includeTools: true });
  
  return {
    messages: [],
    tools: [],
  };
}

export const runtimeConfig = {
  type: 'openclaw',
  supportsStreaming: true,
  supportsSubagents: true,
  maxConcurrent: 8,
};
`;
  }
  
  if (adapterType === 'claude-code') {
    return `// Claude Code Runtime Adapter for ${spec.agentId}
// This adapter integrates the harness with Claude Code CLI

import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export async function spawnAgent(task, options = {}) {
  const claudeArgs = [
    '--prompt',
    JSON.stringify(task),
    options.model ? \`--model \${options.model}\` : '',
  ].filter(Boolean).join(' ');
  
  const { stdout, stderr } = await execAsync(\`claude \${claudeArgs}\`);
  
  return {
    output: stdout,
    error: stderr,
    sessionKey: null, // Claude Code doesn't have persistent sessions
  };
}

export async function getAgentOutput(sessionKey) {
  throw new Error('Claude Code adapter does not support session retrieval');
}

export const runtimeConfig = {
  type: 'claude-code',
  supportsStreaming: false,
  supportsSubagents: false,
  maxConcurrent: 1,
};
`;
  }
  
  // Custom adapter template
  return `// Custom Runtime Adapter for ${spec.agentId}
// Implement the adapter interface for your custom runtime

export async function spawnAgent(task, options = {}) {
  // TODO: Implement agent spawning for your runtime
  throw new Error('Not implemented');
}

export async function getAgentOutput(sessionKey) {
  // TODO: Implement output retrieval for your runtime
  throw new Error('Not implemented');
}

export const runtimeConfig = {
  type: 'custom',
  supportsStreaming: false,
  supportsSubagents: false,
  maxConcurrent: 1,
};
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function getVoiceForRole(role: string): string {
  const roleLower = role.toLowerCase();
  if (roleLower.includes('research')) return 'Analytical, curious, thorough. Cite sources.';
  if (roleLower.includes('engineer') || roleLower.includes('dev')) return 'Technical, precise, pragmatic. Code-first.';
  if (roleLower.includes('writer') || roleLower.includes('content')) return 'Creative, engaging, clear. Voice matters.';
  if (roleLower.includes('coach') || roleLower.includes('lifecoach')) return 'Supportive, direct, action-oriented. Push growth.';
  if (roleLower.includes('financial') || roleLower.includes('tax')) return 'Conservative, detail-oriented, compliant. Numbers first.';
  if (roleLower.includes('architect')) return 'Strategic, opinionated, well-researched. Design patterns matter.';
  return 'Professional, helpful, efficient. Get the job done.';
}

function generateToolPattern(tool: any): string {
  return `### ${tool.name}
**When to use:** [context where this tool is appropriate]
**How to use:** 
\`\`\`
// Example usage
\`\`\`
**Common pitfalls:** [what goes wrong]
**Error handling:** [how to recover]`;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}
